##
## EPITECH PROJECT, 2020
## ex01
## File description:
## Makefile
##

SRC	=	hex_to_base64.py

NAME	=	challenge01

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
