##
## EPITECH PROJECT, 2020
## ex05
## File description:
## Makefile
##

SRC	=	repeat_key_xor.py

NAME	=	challenge05

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
