##
## EPITECH PROJECT, 2020
## experiencePython
## File description:
## Makefile
##

all:
	@echo "================== HELP =================="
	@echo "|  Use make run to execute the program   |"
	@echo "=========================================="

run:
	@python src/main.py