##
## EPITECH PROJECT, 2020
## ex01
## File description:
## Makefile
##

SRC	=	detectSingleByteXOR.py

NAME	=	challenge04

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
