##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## make / clean / fclean / re
##

SRC	=	107transfer.go

NAME	=	107transfer

all: $(NAME)

$(NAME):
	go build -o $(NAME) $(SRC)

clean:
	rm $(NAME)

fclean:	clean

re: fclean all
