##
## EPITECH PROJECT, 2020
## ex07
## File description:
## Makefile
##

SRC	=	aes_ecb_mode.py

NAME	=	challenge07

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
