##
## EPITECH PROJECT, 2020
## CNA_groundhog_2019
## File description:
## Makefile
##

all:
	@cp groundhog.py groundhog
	@chmod +x groundhog
	@echo "Binary ready! Groundhog is born !"

clean:
	@rm -rf *~
	@echo "Removed all tmp files."

fclean:	clean
		@rm -rf groundhog
		@echo "Removed Binary.... no more groundhog here !"

re: fclean all
