jenkins:

  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true

  securityRealm:
    local:
      enableCaptcha: false
      allowsSignup: false
      users:
        - id: chocolateen
          name: Hugo
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          name: Garance
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          name: Jeremy
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          name: Nassim
          password: ${USER_NASSO_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: admin
          assignments:
            - chocolateen
          description: Marvin master
          permissions:
            - Overall/Administer
        - name: ape
          assignments:
            - i_dont_know
          description: Pedagogical team member
          permissions:
            - Overall/Read
            - Job/Read
            - Job/Build
            - Job/Workspace
        - name: gorilla
          assignments:
            - vaugie_g
          description: Group Obsessively Researching Innovation Linked to Learning and Accomplishment
          permissions:
            - Overall/Read
            - Job/Read
            - Job/Build
            - Job/Workspace
            - Job/Create
            - Job/Configure
            - Job/Delete
            - Job/Move
            - Job/Cancel
        - name: assist
          assignments:
            - nasso
          description: Assistant
          permissions:
            - Overall/Read
            - Job/Read
            - Job/Workspace

jobs:
  - script: >
      folder('Tools') {
        description('Folder for miscellaneous tools.')
      }

      job('Tools/clone-repository') {
        disabled(false)
        parameters {
          stringParam('GIT_REPOSITORY_URL', null, 'Git URL of the repository to clone')
        }
        wrappers {
          preBuildCleanup()
        }
        steps {
          shell('git clone $GIT_REPOSITORY_URL')
        }
      }

      job('Tools/SEED') {
        parameters {
          stringParam('GITHUB_NAME', null, 'GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")')
          stringParam('DISPLAY_NAME', null, 'Display name for the job')
        }
        steps {
          dsl {
            text('''job("$DISPLAY_NAME")) {
              scm {
                github("$GITHUB_NAME")
              }
              wrappers {
                preBuildCleanup()
              }
              triggers {
                periodic(1)
              }
              steps {
                shell(\'make fclean\')
                shell(\'make\')
                shell(\'make test\')
                shell(\'make clean\')
              }
            }''')
          }
        }
      }
