##
## EPITECH PROJECT, 2020
## ex10
## File description:
## Makefile
##

SRC	=	server_ecb_decryption.py

NAME	=	challenge10

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
