#!/usr/bin/env python3

import sys

USAGE = '''USAGE
    ./308reedpipes r0 r5 r10 r15 r20 n
DESCRIPTION
    r0      radius (in cm) of pipe at the 0cm abscissa
    r5      radius (in cm) of pipe at the 5cm abscissa
    r10     radius (in cm) of pipe at the 10cm abscissa
    r15     radius (in cm) of pipe at the 15cm abscissa
    r20     radius (in cm) of pipe at the 20cm abscissa
    n       number of points needed to display the radius
'''

class   Reedpipes():
    result, ordinate, abscissa, vector = [], [], [0, 5, 10, 15, 20], [0, None, None, None, 0]
    var = {'r0': 0, 'r5': 0, 'r10': 0, 'r15': 0, 'r20': 0, 'n': 0}

    def __init__(self, argument, total=0):
        for arg, i in zip(self.var, range(1, len(argument))):
            self.var[arg] = float(argument[i])
            if self.var[arg] is not self.var['n']:
                self.ordinate.append(self.var[arg])

    def computeValue(self): 
        self.vector[2] = ((6 * (self.var['r15'] - 2 * self.var['r10'] + self.var['r5']) / 50) - ((6 * (self.var['r10'] - 2 * self.var['r5'] + self.var['r0']) / 50) + (6 * (self.var['r20'] - 2 * self.var['r15'] + self.var['r10']) / 50)) / 4) * 4 / 7
        self.vector[1] = (6 * (self.var['r10'] - 2 * self.var['r5'] + self.var['r0']) / 50) / 2 - 0.25 * self.vector[2]
        self.vector[3] = (6 * (self.var['r20'] - 2 * self.var['r15'] + self.var['r10']) / 50) / 2 - 0.25 * self.vector[2]
        for d in range(int(self.var['n'])):
            X = 20 / (self.var['n'] - 1) * d
            i = int((X - 0.01) / 5) + 1
            self.result.append(
                (- self.vector[i - 1] / 30 * pow(X - self.abscissa[i], 3) + self.vector[i] / 30 * pow(X - self.abscissa[i - 1], 3) - (self.ordinate[i - 1] / 5 - 5 / 6 * self.vector[i - 1]) * (X - self.abscissa[i]) + (self.ordinate[i] / 5 - 5 / 6 * self.vector[i]) * (X - self.abscissa[i - 1]))
            )

    def printValue(self):
        print(f"vector result: [{self.vector[0] if round(self.vector[0], 1) != 0 else 0:.1f}, {self.vector[1] if round(self.vector[1], 1) != 0 else 0:.1f}, {self.vector[2] if round(self.vector[2], 1) != 0 else 0:.1f}, {self.vector[3] if round(self.vector[3], 1) != 0 else 0:.1f}, {self.vector[4] if round(self.vector[4], 1) != 0 else 0:.1f}]")
        for i in range(int(self.var['n'])):
            print(f"abscissa: {20 / (self.var['n'] - 1) * i:.1f} cm\tradius: {(self.result[i]):.1f} cm")

def main():
    global USAGE
    if len(sys.argv) != 7:
        print(USAGE)
        if len(sys.argv) == 2 and ("-h" in sys.argv or "--help" in sys.argv):
            return 0
        return 84
    try:
        for arg in sys.argv[1:]:
            if float(arg) <= 0:
                return 84
        obj = Reedpipes(sys.argv)  
        obj.computeValue()
        obj.printValue()
    except:
        return 84
    return 0

if __name__ == "__main__":
    sys.exit(main())
