##
## EPITECH PROJECT, 2020
## ex03
## File description:
## Makefile
##

SRC	=	single_byte_xor.py

NAME	=	challenge03

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
