##
## EPITECH PROJECT, 2020
## ex08
## File description:
## Makefile
##

SRC	=	detect_aes_ecb_mode.py

NAME	=	challenge08

.PHONY:	all	exe	clean	fclean	re

all:	exe

exe:
		cp $(SRC) $(NAME)
		chmod +x $(NAME)

fclean:
		rm -f $(NAME)

re:	fclean all
