##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## make / clean / fclean / re
##

SRC	=	108trigo.go	\
		calcul_sec.go	\

NAME	=	108trigo	\

all: $(NAME)

$(NAME):
	go build -o $(NAME) $(SRC)

clean:
	rm $(NAME)

fclean:	clean

re: fclean all
